### PR TITLE
Create Angular version of Friendlychat

### PR DESCRIPTION
**Pull request by jmdobry**

### CODE REVIEW

**Comment by jmdobry** [comment]
PTAL @jamesdaniels @katowulf @davideast

**Comment by jmdobry** [comment]
If any of you want to test this out (please 😄 ), the codelab is published here: https://codelabs.developers.google.com/codelabs/firebase-cloud-functions-angular

Instead of `git clone https://github.com/firebase/friendlychat` you'll want:

```
git clone https://github.com/jmdobry/friendlychat
git checkout angular
```

cc @bretmcg

**Comment by nicolasgarnier** [comment]
Hey @jmdobry,

This codelab seems very similar to the [non-angular Cloud Functions codelab](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions-angular)

**Comment by nicolasgarnier** [comment]
Hey @jmdobry,

This codelab seems very similar to the [non-angular Cloud Functions codelab](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions) (with one extra step "Sentiment Analysis" which is cool) but it does not really show how to build the angular front-end which, just like the pure JS client in the **non-angular Cloud Functions codelab**, serves mainly as a way to see the results of the Cloud Functions in action.

Here is what I propose, let me know how that sounds:

 - Add the extra Cloud Function step (Sentiment analysis) to the existing Cloud Functions codelab (I can give you access to the codelab instructions document). I guess there is a small change to the frontend to do so that it displays the sentiment in some way? (Or a way to do this without changes to the frontend would be to append a smiley that correspond to the mood of the message)
 - Build an entirely new frontend codelab that shows how to build the frontent with Angular and Firebase. That would be quite interesting as we often get requests about more framework oriented codelabs and samples.

let me know what you think, happy to discuss :)

**Comment by jmdobry** [comment]
@nicolasgarnier Talking with @jamesdaniels, I think the plan _is_ to add the sentiment analysis step to the non-Angular Cloud Functions sample/codelab, and also add the Angular version of friendlychat under `web-angular` and `web-angular-start`. I didn't have time to do all of that for my workshop on Angular/Firebase/Cloud Functions today at 1pm MT.

The code in this PR is meant to be used with: https://codelabs.developers.google.com/codelabs/firebase-cloud-functions-angular

**Comment by jamesdaniels** [comment]
I'm gonna merge so we can do the workshop today. @nicolasgarnier we're planning both things you suggested, we just didn't want to put non-angular code in the hands of people at ng-conf.

**Comment by nicolasgarnier** [comment]
OK that all makes sense then :)

**Pull request merged**
